app:
  geometry: "1500x900+300+85"
  templates:
    width: 6
    allow_none: True
  interfaces:
    width: 12
    allow_none: False

database:
  host: localhost            # by default
  port: 5432                 # by default
  database: device_registry  # by default
  username: postgres         # by default ; rename to auth_username
  password: postgres         # by default ; rename to auth_password

tftp-server:
  address: 192.168.3.105
  port: 69
  folder: /srv/tftp

host:
  username: [admin, mvsadmin]
  password: [admin, MVS_admin, password, '1234']
  address: [192.168.1.1, 192.168.0.1, 10.4.0.3]
  port: ['22']

default-cert: MVS
serial-port: /dev/ttyUSB0
mvs-network: 192.168.3.0/24
backup-folder: ./.backups/
