database:
  host: localhost            # by default
  port: 5432                 # by default
  database: device_registry  # by default
  username: postgres         # by default
  password: postgres         # by default

tftp-server:
  address: 10.3.1.144
  port: 69
  folder: /srv/tftp

host:
  username: mvsadmin    # by default
  password: MVS_admin   # by default
  network: 10.4.0.0/24  # service_network: 192.168.3.0/24, mgmt_network: 10.4.0.0/24

app:
  templates:
    width: 6
    allow-none: True
  interfaces:
    width: 12
    allow-none: False


serial:
  port: /dev/ttyUSB0
  baudrate: 115200
  parity: None
  bitesize: 8
  stopbits: 1
  timeout: 1
  flow-control:
    xonxoff: False
    rtscts: False
    dsrdtr: False

backup-folder: ./backups
