app:
  geometry: "1400x1000+300+100"
  templates:
    width: 6
    allow-none: True
  interfaces:
    width: 12
    allow-none: False

database:
  host: localhost            # by default
  port: 5432                 # by default
  database: device_registry  # by default
  username: postgres         # by default ; rename to auth_username
  password: postgres         # by default ; rename to auth_password

tftp-server:
  address: 10.4.0.155
  port: 69
  folder: /srv/tftp

host:
  username: mvsadmin
  password: MVS_admin
  address: 10.4.0.3
  port: 22

default-cert: MVS
serial-port: /dev/ttyUSB0
mvs-network: 192.168.3.0/24
backup-folder: ./.backups/
