database:
  host: localhost            # by default
  port: 5432                 # by default
  database: device_registry  # by default
  username: postgres         # by default
  password: postgres         # by default

tftp-server:
  address: 192.168.3.144
  port: 69
  folder: /srv/tftp

host:
  username: admin
  password: admin
  address: 192.168.3.187
  port: 22

ssh-config-file: ~/NetDevConfigurator/src/config/ssh.conf  # unused in last versions

app:
  templates:
    width: 6
    allow-none: True
  interfaces:
    width: 12
    allow-none: False


serial-port: /dev/ttyUSB0

backup-folder: ./backups
