database:
  host: localhost
  port: 5432
  database: device_registry
  username: postgres
  password: postgres

tftp-server:
  address: 10.3.1.144
  port: 69
  folder:
    config: tmp
    firmware: firmware

ssh-config-file: ~/NetDevConfigurator/src/config/ssh.conf

backup-folder: ./backups
