app:
  grid_columns: 8  # Number of columns in the grid layout
  templates:
    width: 6
    allow_none: True
  interfaces:
    width: 12
    allow_none: False

database:
  host: localhost            # by default
  port: 5432                 # by default
  database: device_registry  # by default
  username: postgres         # by default
  password: postgres         # by default

tftp-server:
  address: 192.168.3.105
  port: 69
  folder: /srv/tftp

host:
  address: [79.134.218.38, 192.168.3.201, 192.168.0.1, 10.4.0.3]
  port: ['22']
  username: [admin, mvsadmin]
  password: [MVS_admin, MVS_admin20, admin, password, '1234']

default-cert: MVS
serial-port: /dev/ttyUSB0
mvs-network: 192.168.3.0/24
backup-folder: ./.backups/
