PUBLIC_IP: 192.168.3.231             # IP адрес в больничной сети
PUBLIC_MASK: 255.255.255.0           # Маска сети больничной сети
GW: 192.168.3.1                      # IP адрес шлюза в больничной сети
# MODEL: 3                             # Модель маршрутизатора: 1) ESR20; 2) ESR21; 3) ESR31
VERS: 1                              # Версия прошивки маршрутизатора: 1.23 и более новая: 1) Да; 2) Нет
TYPE_COMPLEX: 1                      # Комплектация MVS комплекса: 1) Standart; 2) All-In-One
STREAM_COUNT: 13                     # Количество стримеров
VPN: 1                               # Настроить ВПН сервер: 1) Да; 2) Нет
TELEPORT: 2                          # Телепорт включен в состав комплекса: 1) Да; 2) Нет
PH_COUNT: 15                          # Количество пакгаусов (при наличии Телепорта)
RAISA: 1                             # РАИСа включена в состав комплекса: 1) Да; 2) Нет
RAISA_IP: 192.168.3.232              # IP адрес для сервера РАИСы (при включении РАИСЫ в состав комплекса)
TRUECONF: 1                          # Trueconf сервер включен в состав комплекса: 1) Да; 2) Нет
TRUEROOM: 1                          # Trueconf Room включена в состав комплекса: 1) Да; 2) Нет
TRUEROOM_COUNT: 20                   # Количество Trueconf Room (учитывается при включении Trueconf Room в состав комплекса)
TRUEROOM_IP1: 192.168.3.233          # Trueconf Room 1 IP адрес (если комнат больше чем 1, добавить аналогичные строки для TRUEROOM_IP2, TRUEROOM_IP3 и т.д.)
